name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the Go toolchain
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      # Step 3: Build the app using the buildprod.sh script
      - name: Build the app
        run: scripts/buildprod.sh

      # Step 4: Authenticate with GCP
      - name: 'Authenticate with GCP'
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 5: Set up Google Cloud SDK (gcloud)
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      # Step 6: Verify gcloud CLI is set up
      - name: 'Use gcloud CLI'
        run: gcloud info

      # Step 7: Configure Docker to use gcloud as a credential helper for Artifact Registry
      - name: 'Configure Docker authentication with GCP'
        run: gcloud auth configure-docker us-east4-docker.pkg.dev

      # Step 8: Build and push Docker image to Google Artifact Registry
      - name: 'Build and push Docker image'
        run: gcloud builds submit --tag us-east4-docker.pkg.dev/notely-435521/notely-ar-repo/notely:latest .

      # Step 9: Deploy to Running Docker Container
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-east4-docker.pkg.dev/notely-435521/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project '${{ secrets.GCP_PROJECT_ID }}' --max-instances=4